CREATE TABLE [fis].[DocTax2]
(
	[DocTax2Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY CLUSTERED ([DocTax2Id]),
	[DocTax2Name] NVARCHAR(128) NOT NULL,
	[PDocTax2] NUMERIC(20,3) NULL,
	[DebitAcc] NVARCHAR(10) NULL,
	[CreditAcc] NVARCHAR(10) NULL,
)
