CREATE TABLE [fis].[DocTax1]
(
	[DocTax1Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY CLUSTERED ([DocTax1Id]),
	[DocTax1Name] NVARCHAR(128) NOT NULL,
	[PDocTax1] NUMERIC(20,3) NULL,
	[DebitAcc] NVARCHAR(10) NULL,
	[CreditAcc] NVARCHAR(10) NULL,
)
